### ISSUE TITLE
Update to 1.14?

### ISSUE THREAD

**Issue by JRaspass** [gplessis/dotdeb-nginx#105]
As per title, I believe 1.14 is the latest stable.

**Comment by gplessis** [comment]
Once 1.14 hits [stretch-backports](https://packages.debian.org/stretch-backports/nginx), I could consider it. I just don’t want Dotdeb users to be stuck with an outdated 1.14 if they upgrade their Jessie+Dotdeb machines to Stretch in the future. Stay tuned...

**Comment by brechsteiner** [comment]
Are there any plans to update to Nginx 1.13.3-1 (Stretch Backports) on Debian Jessie?

**Comment by gplessis** [comment]
@JRaspass did you read my previous comment? Both Stretch-backports and Buster are stuck with 1.13

**Comment by gplessis** [comment]
@brechsteiner why duplicate the effort if it's already present in Stretch-backports? I'll wait for 1.14 to be packaged.

**Comment by brechsteiner** [comment]
because the packages from dotdeb have compiled many more modules, for example ldap-auth and naxsi

**Comment by gplessis** [comment]
Work in progress 🎉

**Comment by gplessis** [comment]
Nginx 1.14.1 is now available for Jessie: 
https://www.dotdeb.org/2018/11/12/nginx-1-14-1-for-jessie/

**Comment by brechsteiner** [comment]
cool, thx
