### ISSUE TITLE
old mime.types

### ISSUE THREAD

**Issue by mikeyh** [gplessis/dotdeb-nginx#55]
Hi, it looks like some of the config files in wheezy/debian/conf are really old. eg mime.types

The latest upstream versions in wheezy/conf do not seem to be used.

**Comment by gplessis** [comment]
mime.types have been updated in 56d395db7619b53a62114aa9670fe213b903d788. Be sure to accept this latest version when upgrading your packages.

**Comment by bbak** [comment]
Maybe you could add these additional mime.types [for fonts](http://stackoverflow.com/questions/28235550/proper-mime-type-for-woff2-fonts):
```
font/woff2                       woff2;
font/opentype                    otf;
font/truetype                    ttf;
```
