### ISSUE TITLE
update nginx ldap module

### ISSUE THREAD

**Issue by sts** [gplessis/dotdeb-nginx#56]
[There have been two fixes we were able to contribute to the nginx-auth-ldap module](https://github.com/kvspb/nginx-auth-ldap/pull/65), already merged upstream. We are using dotdeb for our packages, so we would love to see the changes in the upcoming Dotdeb Nginx release.

**Comment by gplessis** [comment]
I'll see what I can do for the next Nginx stable release. Thanks.

**Comment by gplessis** [comment]
Fixed in 8c2a92f476a82b87aeaf1d3c211f39eb31212b18
