### ISSUE TITLE
php5-fpm broken with nginx 1.8 on wheezy

### ISSUE THREAD

**Issue by tgabi333** [gplessis/dotdeb-nginx#63]
i just installed nginx 1.8 and my site broke.

I found that from the new `fastcgi_params` file, SCRIPT_FILENAME  is missing which is required for fpm.

As i see here:
https://github.com/gplessis/dotdeb-nginx/blob/bb80b41173c1e2871a6356a7c109371a29211637/debian/nginx-common.NEWS#L47

debian package maintainers removed the this distro-extra-included line from the default config which now synced with dotdeb-nginx.

So there is two way of solving this problem:
2) Always define SCRIPT_FILENAME parameter in your config, like this:

```
    location ~ ^/index\.php(/|$) {
            fastcgi_split_path_info ^(.+\.php)(.*)$;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $request_filename;
    }
```

2)  Put back the line
```
fastcgi_param   SCRIPT_FILENAME         $request_filename;
```
to your fastcgi_params file.

**Comment by tgabi333** [comment]
As i see here:
https://github.com/gplessis/dotdeb-nginx/blob/bb80b41173c1e2871a6356a7c109371a29211637/debian/nginx-common.NEWS#L47

debian package maintainers removed the this distro-extra-included line from the default config. which now synced with dotdeb-nginx.

**Comment by tholu** [comment]
Recommended solution is to switch from fastcgi_params to fastcgi.conf

**Comment by rockyluke** [comment]
Debian introduce fastcgi.conf in release 1.6.1 (or 1.6.2 I can't remeber). So the solution is to switch from fastcgi_params to fastcgi.conf.

**Comment by gplessis** [comment]
Migrating from `fastcgi_params` to `fastcgi.conf` fixes the problem.

**Comment by clarkk** [comment]
where do I find this `fastcg.conf` ?

**Comment by tholu** [comment]
@clarkk Should be already there.
