### ISSUE TITLE
Adding ngx_pagespeed

### ISSUE THREAD

**Issue by szepeviktor** [gplessis/dotdeb-nginx#67]
Is it possible to add this to nginx-extra?
https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source
I could help integrate in the Debian build process.

**Comment by gplessis** [comment]
It's already included in `nginx-extras`(https://github.com/gplessis/dotdeb-nginx/blob/jessie/debian/rules#L127) but the building process downloads some third-party binary (psol). That's something totally forbidden by the official Debian packaging guidelines.

**Comment by szepeviktor** [comment]
I am sorry.

**Comment by szepeviktor** [comment]
Could `psol` be added as a dependency, a deb package?

**Comment by gplessis** [comment]
It could, but it would require separate packages.
