### ISSUE TITLE
User Agents Containing Lightning Are Blocked

### ISSUE THREAD

**Issue by sinkq-plt** [gplessis/dotdeb-nginx#71]
Distribution: Debian Wheezy
Architecture: Tested on both AMD64 and i386
Nginx Version: 1.8.0
Package Installed: nginx-common nginx-naxsi
User Agent Strings: 'Lightning', 'lightning', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0 SeaMonkey/2.33.1 Lightning/3.8b2'
Problem: User agent containing the word 'Lightning' or 'lightning' is blocked by HTTP code 444. I didn't block the word in any Nginx config files.

**Comment by gplessis** [comment]
Could you please provide your Nginx configuration? Do you really need naxsi?

**Comment by sinkq-plt** [comment]
Sorry, finally realized the silly mistake I've made. Anyway, thanks for the prompt reply.
