### ISSUE TITLE
Custom modules

### ISSUE THREAD

**Issue by colinmollenhour** [gplessis/dotdeb-nginx#74]
Your packages are wonderful to have and it is even better that you have the build source on github! However, for non-package maintainers it is not obvious how to roll your own packages when you unfortunately need to use a custom module. Could you add a basic instruction to the README regarding where to add the --add-module directive (I found that much) and what commands to run to get a .deb file afterwards?

Thanks!

**Comment by gplessis** [comment]
You can add the source of your custom modules to the `debian/modules` subdirectory and edit `debian/rules` to add them to the configure options.

Then, to build the packages, launch these commands : 
```
apt-get install -y build-essential devscripts equivs libwww-perl
mk-build-deps --install --tool 'apt-get -y' --remove /root/control
find debian/ -name '\.git*' -exec rm -rf {} \; &>/dev/null
rm -r debian/modules/nginx-upload-progress/test/
rm -r debian/modules/nginx-rtmp-module/test/
uscan --download-current-version
dpkg-buildpackage
```

**Comment by colinmollenhour** [comment]
Thank you so much! Would you like me to submit a PR with edits to README which add this information?

**Comment by gplessis** [comment]
Don't bother, I'll do it. Thank you :)
