### ISSUE TITLE
upload_progress missing in nginx 1.10

### ISSUE THREAD

**Issue by smelchior** [gplessis/dotdeb-nginx#82]
The nginx 1.10 includes "--add-module=/usr/src/builddir/debian/modules/nginx-upload-progress" in nginx -V but nginx complains that:
nginx: [emerg] unknown directive "upload_progress"

so somehow the module is not active

**Comment by gplessis** [comment]
Duplicates #81

**Comment by smelchior** [comment]
But the fix for #81 does not really fix this issue (only for wheezy, not jessie). Could you reopen this?

**Comment by gplessis** [comment]
@smelchior you're using Jessie, right? Which nginx flavor?

**Comment by smelchior** [comment]
thanks, yes i am using jessie, i am using nginx-full 
here is the full nginx -V
`nginx version: nginx/1.10.1
built with OpenSSL 1.0.1k 8 Jan 2015
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-file-aio --with-threads --with-http_addition_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_secure_link_module --with-http_sub_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-stream=dynamic --with-stream_ssl_module --add-module=/usr/src/builddir/debian/modules/headers-more-nginx-module --add-dynamic-module=/usr/src/builddir/debian/modules/nginx-auth-pam --add-module=/usr/src/builddir/debian/modules/nginx-cache-purge --add-module=/usr/src/builddir/debian/modules/nginx-dav-ext-module --add-dynamic-module=/usr/src/builddir/debian/modules/nginx-development-kit --add-module=/usr/src/builddir/debian/modules/nginx-echo --add-module=/usr/src/builddir/debian/modules/ngx-fancyindex --add-module=/usr/src/builddir/debian/modules/nginx-push-stream-module --add-dynamic-module=/usr/src/builddir/debian/modules/nginx-lua --add-module=/usr/src/builddir/debian/modules/nginx-upload-progress --add-module=/usr/src/builddir/debian/modules/nginx-upstream-fair --add-module=/usr/src/builddir/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/builddir/debian/modules/nginx-auth-ldap --add-module=/usr/src/builddir/debian/modules/ngx_http_pinba_module --add-module=/usr/src/builddir/debian/modules/ngx_pagespeed --add-module=/usr/src/builddir/debian/modules/nginx-x-rid-header --add-module=/usr/src/builddir/debian/modules/nginx-rtmp-module --with-ld-opt=-lossp-uuid
`

include /etc/nginx/modules-enabled/*.conf; is included in my nginx.conf but that does not matter anyway i guess as uploadprogress is still compiled as a static module.

**Comment by olivier-monaco** [comment]
Same problem on Wheezy.

**Comment by gplessis** [comment]
Ok. I can reproduce the issue and I'm currently investigating.

**Comment by gplessis** [comment]
ok, got it. <tt>nginx-upload-progress</tt> was never part of <tt>nginx-full</tt> and for an unknown reason <tt>nginx -V</tt> output is wrong.

Could you please install <tt>nginx-extras</tt> instead and keep me posted?

**Comment by smelchior** [comment]
dito, the nginx-extras package does not fix this

**Comment by gplessis** [comment]
This issue should be fixed with versions : 
* `1.10.1-1~dotdeb+8.2` for Jessie
* `1.10.1-1~dotdeb+7.3` for Wheezy

Please confirm.

**Comment by nathanjahnke** [comment]
nginx config passes now but `received` seems to always equal `size` in the json output. I am not sure if it is my implementation. Can someone else test?

**Comment by smelchior** [comment]
Does not seem to work for me either. The Module is loaded correctly but does not report proper data.
We switched to a different implementation now though, so we do not need the module anymore.

**Comment by nathanjahnke** [comment]
@smelchior Which module do you now use?

**Comment by smelchior** [comment]
we are doing it in JS now, similar to http://stackoverflow.com/questions/15965651/progress-bar-while-uploading-large-files-with-xmlhttprequest

**Comment by dereksmalls** [comment]
Is there any update on this issue?
