### ISSUE TITLE
Dotdeb nginx is compiled against OpenSSL 1.0.1t, and therefore HTTP/2 is not supported in Chrome > v.51

### ISSUE THREAD

**Issue by benjaminblack** [gplessis/dotdeb-nginx#88]
Chrome removed support for NPN starting in version 51:

https://developers.google.com/web/updates/2016/04/chrome-51-deprecations

OpenSSL did not implement ALPN until version 1.0.2:

https://www.openssl.org/news/openssl-1.0.2-notes.html

The version of Nginx packaged by Dotdeb was compiled against OpenSSL v1.0.1t:

`$ nginx -V`
`nginx version: nginx/1.10.2`
`built with OpenSSL 1.0.1t  3 May 2016`
`[...snip...]`

Versions of Chrome > 51 will not upgrade the connection to HTTP/2 without ALPN support.

I checked an identical Nginx configuration in Ubuntu 16.04, which is (currently) Nginx version 1.10.0 and compiled against OpenSSL 1.0.2g, and confirmed that Chrome does upgrade connections to HTTP/2, running the same configuration.

**Comment by gplessis** [comment]
Duplicates #70.

I'll announce this new repo soon.
