### ISSUE TITLE
Streams directive is not avaible

### ISSUE THREAD

**Issue by Danixu** [gplessis/dotdeb-nginx#94]
Hello,

I've tried to use the Dotdeb nginx version because it comes with Naxsi, but I've found that streams are not supported. It gives me an error:
`Feb 15 13:27:27 someserver nginx[7642]: nginx: [emerg] unknown directive "stream" in /etc/nginx/streams-enabled/streams.conf:2`

I comes from the official release and works fine.
What can I do to make it work?. I've installed the nginx-extras package that includes the libnginx-mod-stream module.

Thanks!!

**Comment by gplessis** [comment]
First, please make sure that you installed <tt>nginx-full</tt> or <tt>nginx-extras</tt> (not <tt>nginx-light</tt>). Then verify that you have the following line in your <tt>/etc/nginx/nginx.conf</tt> file : 
```
include /etc/nginx/modules-enabled/*.conf;
```
This line will make sure that streams are loaded, since they're a separate dynamic module.

**Comment by gplessis** [comment]
Did it solve your issue?

**Comment by Danixu** [comment]
Yeah, sorry. I forgot to comment that was solved just loading that files.

Thanks!!!
