### ISSUE TITLE
pagespeed module?

### ISSUE THREAD

**Issue by MyWay** [gplessis/dotdeb-nginx#97]
It seems it's not working...

**Comment by gplessis** [comment]
Please provide more details: distribution, versions, configuration, logs, error messages...

**Comment by MyWay** [comment]
nginx version: nginx/1.10.3
built with OpenSSL 1.0.1t  3 May 2016 (running with OpenSSL 1.0.2k  26 Jan 2017)
If I enable pagespeed module, nginx crashes with worker process "exited on signal 11" and watching to its trace, there is an error related to third_party/serf/instaweb_response_buckets (seems it can't find the file/directory), if you want the entire trace I can post it.

**Comment by MyWay** [comment]
`
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/nginx...Reading symbols from /usr/lib/debug/.build-id/86/60c8a57637cf8dfd7d9dcecb3e7d6a786c7435.debug...done.
done.
[New LWP 9048]
[New LWP 8950]
[New LWP 9046]
[New LWP 8947]
[New LWP 9049]
[New LWP 9047]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process                           '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000b60d92 in serf_bstrmemdup (allocator=0x6d424402aed0, 
    str=0x6d4244007d45 "e\233\247\023\n\300\262\"\211\251?\236W\313P\300\060", 
    size=18446744073709551615) at third_party/serf/instaweb_buckets.c:133
133	third_party/serf/instaweb_buckets.c: File o directory non esistente.
(gdb) backtrace full
#0  0x0000000000b60d92 in serf_bstrmemdup (allocator=0x6d424402aed0, 
    str=0x6d4244007d45 "e\233\247\023\n\300\262\"\211\251?\236W\313P\300\060", 
    size=18446744073709551615) at third_party/serf/instaweb_buckets.c:133
        newstr = 0x6d424400bea8 "e\233\247\023\n\300\262\"\211\251?\236W\313P\300\060"
#1  0x0000000000b64a35 in parse_status_line (ctx=0x6d4244007d08, 
    allocator=0x6d424402aed0)
    at third_party/serf/instaweb_response_buckets.c:148
        res = 1
        reason = 0x6d4244007d45 "e\233\247\023\n\300\262\"\211\251?\236W\313P\300\060"
#2  0x0000000000b64c68 in run_machine (bkt=0x6d424400c5a8, ctx=0x6d4244007d08)
    at third_party/serf/instaweb_response_buckets.c:225
        status = 0
#3  0x0000000000b64fde in serf_bucket_response_status (bkt=0x6d424400c5a8, 
    sline=0x6d425294e980) at third_party/serf/instaweb_response_buckets.c:395
        ctx = 0x6d4244007d08
        status = 27970
#4  0x0000000000ab4e0a in net_instaweb::SerfFetch::ReadStatusLine (
    this=0x6d4244040ac0, response=0x6d424400c5a8)
    at pagespeed/system/serf_url_async_fetcher.cc:517
        status_line = {version = 0, code = 0, reason = 0x0}
        status = 0
---Type <return> to continue, or q <return> to quit---
#5  0x0000000000ab65e8 in net_instaweb::SerfFetch::HandleResponse (
    this=0x6d4244040ac0, response=0x6d424400c5a8)
    at pagespeed/system/serf_url_async_fetcher.cc:481
        status = 11
#6  0x0000000000ab67ef in net_instaweb::SerfFetch::HandleResponse (
    request=0x6d424401d748, response=0x6d424400c5a8, 
    handler_baton=0x6d4244040ac0, pool=0x6d4244034758)
    at pagespeed/system/serf_url_async_fetcher.cc:367
        fetch = 0x6d4244040ac0
#7  0x0000000000b63342 in handle_response (request=0x6d424401d748, 
    pool=0x6d4244034758) at third_party/serf/instaweb_outgoing.c:939
        status = 0
        consumed_response = 0
#8  0x0000000000b636ed in read_from_connection (conn=0x6d4244002ce8)
    at third_party/serf/instaweb_outgoing.c:1134
        dummy1 = 0x6d4244019588
        dummy2 = 0x6d4244019488
        status = 0
        tmppool = 0x6d4244034758
        close_connection = 0
        request = 0x6d424401d748
#9  0x0000000000b638eb in serf__process_connection (conn=0x6d4244002ce8, 
    events=1) at third_party/serf/instaweb_outgoing.c:1255
---Type <return> to continue, or q <return> to quit---
        status = 0
#10 0x0000000000b5f9fa in serf_event_trigger (s=0x46bc120, 
    serf_baton=0x6d4244002cf8, desc=0x46bc318)
    at third_party/serf/src/context.c:226
        conn = 0x6d4244002ce8
        ctx = 0x46bc120
        tdesc = {p = 0x0, desc_type = APR_NO_DESC, reqevents = 0, 
          rtnevents = 0, desc = {f = 0x0, s = 0x0}, client_data = 0x0}
        status = 0
        io = 0x6d4244002cf8
#11 0x0000000000b5fb81 in serf_context_run (ctx=0x46bc120, duration=50000, 
    pool=0x46bc058) at third_party/serf/src/context.c:300
        conn = 0x6d4244002cf8
        status = 0
        num = 0
        desc = 0x46bc318
        ps = 0x46bc1a8
#12 0x0000000000ab874b in net_instaweb::SerfUrlAsyncFetcher::Poll (
    this=0x35940b0, max_wait_ms=50)
    at pagespeed/system/serf_url_async_fetcher.cc:1251
        status = 0
        success = true
        mutex = {mutex_ = 0x3554190}
---Type <return> to continue, or q <return> to quit---
#13 0x0000000000abb91e in net_instaweb::SerfThreadedFetcher::SerfThread (
    this=0x35940b0) at pagespeed/system/serf_url_async_fetcher.cc:954
        kPollIntervalMs = 50
        num_active_fetches = 1
#14 0x0000000000abb9c8 in net_instaweb::SerfThreadedFetcher::SerfThreadFn (
    thread_id=0x46bc630, context=0x35940b0)
    at pagespeed/system/serf_url_async_fetcher.cc:856
        stc = 0x35940b0
#15 0x0000000000aeadad in dummy_worker (opaque=0x46bc630)
    at third_party/apr/src/threadproc/unix/thread.c:142
        thread = 0x46bc630
#16 0x00006d425b6b9064 in start_thread (arg=0x6d425294f700)
    at pthread_create.c:309
        __res = <optimized out>
        pd = 0x6d425294f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {120131620763392, 
                -3629294302539516012, 0, 120131777720416, 120131443246048, 
                120131620763392, 1668175907837736852, 1668195365348865940}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
---Type <return> to continue, or q <return> to quit---
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#17 0x00006d42595a762d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
`

**Comment by MyWay** [comment]
Any news about it?

**Comment by gplessis** [comment]
Could you please retry with the Nginx 1.12+ packages for Jessie with an updated Pagespeed module and share your feedback?

**Comment by MyWay** [comment]
Sure I will, thank you very much.

**Comment by MyWay** [comment]
Still crashing. Do you need the trace?

**Comment by gplessis** [comment]
Please.

**Comment by MyWay** [comment]
It seems fixed with the last release. I will let you know if I see anything.
