### ISSUE TITLE
Cannot install from jessie-nginx-http2, dependency issue 

### ISSUE THREAD

**Issue by tr33m4n** [gplessis/dotdeb-nginx#98]
Hi there,

I recently added the `deb http://packages.dotdeb.org jessie-nginx-http2 all` found here https://www.dotdeb.org/instructions/ ... I already had nginx installed from the default repo's. After attempting to upgrade I get the following:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx : Depends: nginx-full (>= 1.10.3-1~dotdeb+http2+8.1) but it is not going to be installed or
                  nginx-light (>= 1.10.3-1~dotdeb+http2+8.1) but it is not going to be installed or
                  nginx-extras (>= 1.10.3-1~dotdeb+http2+8.1) but it is not going to be installed
         Depends: nginx-full (< 1.10.3-1~dotdeb+http2+8.1.1~) but it is not going to be installed or
                  nginx-light (< 1.10.3-1~dotdeb+http2+8.1.1~) but it is not going to be installed or
                  nginx-extras (< 1.10.3-1~dotdeb+http2+8.1.1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Removing the repo and installing nginx fresh fixes the issue but that's obviously not the desired result, I want my HTTP/2 goodness!

Anybody have any pointers?

**Comment by gplessis** [comment]
First, did you activate the jessie-backports repository from Debian to make sure that the right version of OpenSSL will be installed?

If so, could you please use aptitude or dselect to know which broken dependency prevents "nginx with full HTTP/2 from Dotdeb" from being installed?

Thanks for keeping me posted.

**Comment by tr33m4n** [comment]
Hi @gplessis 

I did indeed enable the jessie-backports repo.

I don't have a great deal of experience with `aptitude` or `dselect`. I tried installing with aptitude, it offered me solutions to my issues, both of which involved removing `nginx` and `nginx-full`. At one point it mentioned `nginx-full : Depends: libssl1.0.0 (>= 1.0.2~beta3) but 1.0.1t-1+deb8u6 is installed.` Does that help?

**Comment by gplessis** [comment]
Could you please run `apt-get install -t jessie-backports libssl1.0.0` before trying to upgrade nginx using Dotdeb?

**Comment by tr33m4n** [comment]
@gplessis Ah, yep that fixed it, thanks for the help!
