### ISSUE TITLE
installing nginx-extras with http2 error

### ISSUE THREAD

**Issue by vishalv26** [gplessis/dotdeb-nginx#99]
The following packages have unmet dependencies:
 nginx-extras : Depends: libssl1.0.0 (>= 1.0.2~beta3) but 1.0.1t-1+deb8u6 is to be installed

this is the error i get while installing nginx-extras with http2 without http2 it gets installed.

DEbian 8 Os

**Comment by gplessis** [comment]
Could you please make sure to install libssl1.0.0 from the Jessie backports before installing Nginx from Dotdeb?
`apt-get install -t jessie-backports libssl1.0.0`

**Comment by vishalv26** [comment]
yeah i did 

`apt-get install -t jessie-backports openssl`

it would be better if you proactively add one liner in instructions page.

You're awesome. Thanks!
